settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: safe-ts5-dev
    name: safe.ts5.dev
    url: 'https://safe.ts5.dev/'
    method: GET
    expectStatus: 200

  - id: panel-ts5-dev
    name: panel.ts5.dev
    url: 'https://panel.ts5.dev/auth/login'
    method: GET
    expectStatus: 200

  - id: pandora-ts5-dev
    name: pandora.ts5.dev
    url: 'https://pandora.ts5.dev/'
    method: GET
    expectStatus: 401
 
  - id: nxc-ts5-dev
    name: nxc.ts5.dev
    url: 'https://nxc.ts5.dev/login'
    method: GET
    expectStatus: 200

  - id: jelly-ts5-dev
    name: jelly.ts5.dev
    url: 'https://jelly.ts5.dev/web/index.html#!/login.html'
    method: GET
    expectStatus: 200

  - id: git-ts5-dev
    name: git.ts5.dev
    url: 'https://git.ts5.dev/'
    method: GET
    expectStatus: 200
